import { chromium } from "file:///C:/Users/kh491/OneDrive/Desktop/landings/nova/node_modules/playwright/index.mjs";
const base = process.argv[2] || "http://localhost:3277";
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1440, height: 1000 } })).newPage();
const errors = [];
p.on("pageerror", (e) => errors.push(e.message.slice(0, 200)));
p.on("console", (m) => m.type() === "error" && errors.push(m.text().slice(0, 200)));
await p.goto(base + "/app/eligibility", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(4000);
await p.getByRole("button", { name: /run check/i }).click();
await p.waitForTimeout(6500);
await p.screenshot({ path: "shots/flow-check.png" });
console.log("decision text:", (await p.locator("main").innerText()).match(/UNKNOWN|INELIGIBLE|ELIGIBLE|CONDITIONAL/g)?.slice(0, 3));
await p.goto(base + "/developers/api", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(4000);
await p.getByRole("button", { name: /run request/i }).first().click();
await p.waitForTimeout(3500);
await p.locator("#eligibility-check").screenshot({ path: "shots/flow-api.png" });
console.log(errors.length ? "ERRORS " + errors.join("\n") : "no errors");
await b.close();
